name: Java CI with Maven
on:
  push:
    branches: '**'
  pull_request:
    branches: [ main ]
jobs:
  build:
    strategy:
      matrix:
        java: [ 25, 21, 17 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v5
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v5
      with:
        cache: 'maven'
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Install
      run: ./mvnw install -DskipTests
    - name: Test
      run: ./mvnw -Ptestcontainers verify
